version: "3"
services:
  pacs:
    container_name: orthanc
    image: jodogne/orthanc-plugins
    ports:
      - 8082:8042
      - 4242:4242
    volumes:
      - ./.docker/orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
      - orthanc-storage:/var/lib/orthanc/db
    restart: always
    environment:
      - OrthancBaseUrl="http://xziry.local/orthanc"
    depends_on:
      - orthanc-index
    # networks:
    #   - pacs

  orthanc-index:
    image: postgres:latest
    environment:
      - POSTGRES_USER=orthancu
      - POSTGRES_PASSWORD=orthancp
      - POSTGRES_DB=orthanc
    volumes:
      - orthanc-index:/var/lib/postgresql/data
  # ohif_viewer:
  #   container_name: ohif
  #   image: ohif-viewer # Built after having run: docker build -t ohif-viewer .
  #   # build:
  #   #   context: .
  #   ports:
  #     - 3000:80
  #   environment:
  #     - REACT_APP_DICOMWEB_ENDPOINT=http://xziry.local/orthanc/dicom-web
  #     # volumes:
  #     #   - ./:/usr/src/app
  #     # - ./nginx_ohif.conf:/etc/nginx/conf.d/default.conf:ro
  #     # - ./ohif.js:/usr/share/nginx/html/app-config.js:ro
  #     # - ./logo.png:/usr/share/nginx/html/logo.png:ro
  #   restart: always
  #   # networks:
  #   #   - pacs

volumes:
  orthanc-index:
  orthanc-storage:

    # networks:
    #   pacs:
    #     external: true
